### PR TITLE
Resolve add microsoft authentication

### LINKED ISSUE #2: [Frontend] Feat/Authenticate with Microsoft
### Description
Integrate with `Microsoft` to authenticate users with `@rmit.edu.vn`
### Acceptance criteria

- Successfully `login` and `logout` with `Microsoft`
- Disable account that does not end with `@rmit.edu.vn`

### PR DESCRIPTION
**Pull request by dangvuthang**
### Changelog

- Add `SignInButton` and `SignOutButton` component
- Configure to log in with `Microsoft` account (only **@rmit.edu.vn**)
- Create `useAccessToken` custom hook to gain access token for future use

### How to test

- `checkout` this branch
- Run `npm install`
- Copy `.env.local` from **Team** to folder frontend
- Run `npm run dev`

### Expected result

- Ensure that only account with `@rmit.edu.vn` can log in
- Check console to see `account` return from `Microsoft`

close #2

### CODE REVIEW

**Review by tuanhoang-hub — CHANGES_REQUESTED** [review]
I can not click on the Sign In button. The console sent out 4 times undefined and false.

**Comment by dangvuthang** [comment]
> I can not click on the Sign In button. The console sent out 4 times undefined and false.

Have you copied the file `.env.local` from Team that I upload to folder frontend?

**Comment by tuanhoang-hub** [comment]
> > I can not click on the Sign In button. The console sent out 4 times undefined and false.
> 
> Have you copied the file `.env.local` from Team that I upload to folder frontend?

Yes, I did

**Comment by dangvuthang** [comment]
> > > I can not click on the Sign In button. The console sent out 4 times undefined and false.
> > 
> > 
> > Have you copied the file `.env.local` from Team that I upload to folder frontend?
> 
> Yes, I did

Can you take a screenshot of the console as well as the structure of your frontend folder. Thanks

**Comment by tuanhoang-hub** [comment]
> > > > I can not click on the Sign In button. The console sent out 4 times undefined and false.
> > > 
> > > 
> > > Have you copied the file `.env.local` from Team that I upload to folder frontend?
> > 
> > 
> > Yes, I did
> 
> Can you take a screenshot of the console as well as the structure of your frontend folder. Thanks
bug-microsoft-login
bug-microsoft-login-1
bug-microsoft-login-2

**Comment by dangvuthang** [comment]
> 

Try changing the file name `env.download` to `.env.local`, the problem occurs due to env variable does not load correctly

**Comment by tuanhoang-hub** [comment]
> > 
> 
> Try changing the file name `env.download` to `.env.local`, the problem occurs due to env variable does not load correctly

Ok now it works successfully.

**Review by tuanhoang-hub — APPROVED** [review]

**Pull request merged**
